import MyProject.am1_9
import MyProject.am10_4
import MyProject.am10_5
import MyProject.am10_13

/-
  # Proposition 10.15
  Let `A` be a Noetherian ring, and `Â` its `a`-adic completion. Then
  i) `â = Âa ≅ Â ⨂ a`.
  ii) `(aⁿ)^ = (â)ⁿ`.
  iii) `aⁿ/aⁿ⁺¹ ≅ âⁿ/âⁿ⁺¹`.
  iv) `â` is contained in the Jacobson radical of `Â`.
-/

variable {A : Type*} [CommRing A] (I : Ideal A) [IsNoetherianRing A]


-- Note: here we take `â` to be the `a`-adic completion of `a`. This makes it an `Â`-module.
-- We could also define `â` to be the ideal in `Â` generated by `a`. This gives it an ideal
-- structure. Which one should we use?
noncomputable def am10_15_i :
    AdicCompletion I I ≃ₗ[AdicCompletion I A] TensorProduct A (AdicCompletion I A) I :=
  (AdicCompletion.ofTensorProductEquivOfFiniteNoetherian I I).symm

lemma am10_15_ii (n : ℕ) : true := sorry
lemma am10_15_iii (n : ℕ) : true := sorry
lemma am10_15_iv : true := sorry
