import Mathlib


-- 7.5 Polynomial.isNoetherianRing

-- 10.14 If A is a Noetherian Ring, I an ideal and A' the I-adic completion of A, then A' is a flat A-algebra

lemma am10_14 {A : Type*} [CommRing A] (I : Ideal A) [hN: IsNoetherianRing A] : Module.Flat A (AdicCompletion I A) := by 
  exact AdicCompletion.flat_of_isNoetherian I




-- 10.15.
  --i. If A is Noetherian, A' its I-adic completion, then I' = A' ⊗ I.
  -- use AdicCompletion.coe_ofTensorProductEquivOfFiniteNoetherian?
  -- is I' the I-adic completion of I as an A-module? or should i have it be the ideal of A' generated by I... Use I.map AdicCompletion.ofTensorProduct




theorem am10_15_i {R : Type*} [CommRing R] (I : Ideal R) [hN : IsNoetherianRing R] : 
  TensorProduct R (AdicCompletion I R) I = AdicCompletion I I := by-- should be iso ≃ₗ[AdicCompletion I R]  instead of equality... but then its not a proposition
    
    sorry



theorem am10_15_i2 {R : Type*} [CommRing R] (I : Ideal R) [hN : IsNoetherianRing R] : 
  TensorProduct R (AdicCompletion I R) (↥I) = AdicCompletion I (↥I) := by
    sorry



--ii. (I')^n = (I^n)'





-- 10.22.i
-- inspiration GradedRing.GradeZero.isNoetherianRing

--lemma GradedRing.ofNoetherian.isNoetherian {A: Type*} [Ring A] [IsNoetherianRing A]


-- 10.25

-- 10.26
theorem AdicCompletion.ofNoetherianRing.isNoetherianRing {A : Type*} [CommRing A] (I : Ideal A) [h: IsNoetherianRing A] : IsNoetherianRing (AdicCompletion I A) := by
  sorry
